name: metoid_ks
channels:
  - bioconda
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - samtools=1.9
  - pigz
  - fastqc
  - fastp
  - multiqc
  - pandas
  - biopython
  - kraken2
  - krona
  - bwa
  - bedtools
  - kaiju=1.7.3
  - centrifuge
  - porechop
  
